#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tunarr"
name = "Tunarr"
description.en = "Create live TV channels from media"
description.fr = "Créer des chaînes de télévision en direct à partir de médias"

version = "1.3.10~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Zlib"
website = "https://tunarr.com/"
admindoc = "https://tunarr.com/"
code = "https://github.com/chrisbenincasa/tunarr"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "tunarr"
    amd64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.3.10/tunarr-v1.3.10-linux-x64.tar.gz"
    amd64.sha256 = "b2cfcaad818bcd57b62437dbd6d65d5bcca0ac82b9918888330abd417c07fd5f"
    arm64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.3.10/tunarr-v1.3.10-linux-arm64.tar.gz"
    arm64.sha256 = "cac5ef2935f178d7d885c582901546961a2d7364748cf2d91507e76475a100df"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\-linux-x64"
    autoupdate.asset.arm64 = ".*\\-linux-arm64"

    [resources.sources.ffmpeg]
    amd64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/8.1.2/ffmpeg-n8.1.2-etv-g82f576a8-linux64-gpl-8.1.tar.xz"
    amd64.sha256 = "a2071de14de54931f9e3f7f89ebfb7ddc2de950272529a39e3d82f117f5c52e9"
    arm64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/8.1.2/ffmpeg-n8.1.2-etv-g82f576a8-linuxarm64-gpl-8.1.tar.xz"
    arm64.sha256 = "c573f1c5822677ead8adb258d2d4812878dbf0941ff089ca9ecf685318a29490"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg"
    autoupdate.asset.amd64 = ".*linux64-gpl-.*\\.tar.xz"
    autoupdate.asset.arm64 = ".*linuxarm64-gpl-.*\\.tar.xz"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    
