#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tunarr"
name = "Tunarr"
description.en = "Create live TV channels from media"
description.fr = "Créer des chaînes de télévision en direct à partir de médias"

version = "1.3.13~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Zlib"
website = "https://tunarr.com/"
admindoc = "https://tunarr.com/"
code = "https://github.com/chrisbenincasa/tunarr"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "tunarr"
    amd64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.3.13/tunarr-v1.3.13-linux-x64.tar.gz"
    amd64.sha256 = "177887b75d6837e2313e8f34b3fb0cceec42cfef26b856d23d42e73295e60e46"
    arm64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.3.13/tunarr-v1.3.13-linux-arm64.tar.gz"
    arm64.sha256 = "a45e9f3877536d0ba89da9d9cff5714e4f5bcf403ede18cdba0699a207b4923b"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\-linux-x64"
    autoupdate.asset.arm64 = ".*\\-linux-arm64"

    [resources.sources.ffmpeg]
    amd64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/8.1.2/ffmpeg-n8.1.2-etv-g25d21b2c-linux64-gpl-8.1.tar.xz"
    amd64.sha256 = "4f3cb9c494ebc84e63ae701c59a8523530c7cf1781559427bdf87778a4fee432"
    arm64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/8.1.2/ffmpeg-n8.1.2-etv-g25d21b2c-linuxarm64-gpl-8.1.tar.xz"
    arm64.sha256 = "325e01df9d36b56727ef152192e6fee91431e2c599d899e2a960ba9cb5357fbf"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg"
    autoupdate.asset.amd64 = ".*linux64-gpl-.*\\.tar.xz"
    autoupdate.asset.arm64 = ".*linuxarm64-gpl-.*\\.tar.xz"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    
