#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tunarr"
name = "Tunarr"
description.en = "Create live TV channels from media"
description.fr = "Créer des chaînes de télévision en direct à partir de médias"

version = "1.3.15~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Zlib"
website = "https://tunarr.com/"
admindoc = "https://tunarr.com/"
code = "https://github.com/chrisbenincasa/tunarr"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "tunarr"
    amd64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.3.15/tunarr-v1.3.15-linux-x64.tar.gz"
    amd64.sha256 = "6297e4b4cfe57f222dfb91c1b9a17cc5ceb18a00b5ab1a239e3856f92b3f33eb"
    arm64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.3.15/tunarr-v1.3.15-linux-arm64.tar.gz"
    arm64.sha256 = "7acd33fa85970c14d69b693b103e01eab013927a87922d187740f8ea58a48299"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\-linux-x64"
    autoupdate.asset.arm64 = ".*\\-linux-arm64"

    [resources.sources.ffmpeg]
    amd64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/8.1.2/ffmpeg-n8.1.2-etv-g14f231eb-linux64-gpl-8.1.tar.xz"
    amd64.sha256 = "3b764d897198599e736caa9a1c4c50c211f7ee2bcf0244aecad329ff0cf6f37e"
    arm64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/8.1.2/ffmpeg-n8.1.2-etv-g14f231eb-linuxarm64-gpl-8.1.tar.xz"
    arm64.sha256 = "1a5691b1791877a3fccaa7653943d92ca8300db32b9bc69079c7a08052607d1a"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg"
    autoupdate.asset.amd64 = ".*linux64-gpl-.*\\.tar.xz"
    autoupdate.asset.arm64 = ".*linuxarm64-gpl-.*\\.tar.xz"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    
