#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

ynh_setup_source --dest_dir="$install_dir/ffmpeg" --source_id="ffmpeg"

mv $install_dir/tunarr-* "$install_dir/tunarr"

ynh_exec_as_app $install_dir/tunarr settings update --hide_banner --settings.ffmpeg.ffmpegExecutablePath="$install_dir/ffmpeg/bin/ffmpeg"
ynh_exec_as_app $install_dir/tunarr settings update --hide_banner --settings.ffmpeg.ffprobeExecutablePath="$install_dir/ffmpeg/bin/ffprobe"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add "$app" --description="Create live TV channels from media" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --wait_until="HTTP server listening on host:port"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
